version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: cimg/node:current-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check install
          command: |
            google-chrome --version
            chromedriver --version
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - run:
          name: Chromium Install
          command: node node_modules/puppeteer/install.js
      - run: 
          name: Fixing openspace-api-js type declaration
          command: mkdir node_modules/@types/openspace-api-js;echo "declare module 'openspace-api-js'" >>node_modules/@types/openspace-api-js/index.d.ts
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test
      - store_test_results:
          path: test-results


workflows:
  build_and_test:
    jobs:
      - build
