version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0

executors:
  node-browser:
    docker:
      - image: cimg/node:current-browsers
    working_directory: ~/my-project

jobs:
  test:
    executor: node-browser
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check install
          command: |
            google-chrome --version
            chromedriver --version
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - run:
          name: Chromium Install
          command: node node_modules/puppeteer/install.js
      - run: 
          name: Fixing openspace-api-js type declaration
          command: mkdir node_modules/@types/openspace-api-js;echo "declare module 'openspace-api-js'" >>node_modules/@types/openspace-api-js/index.d.ts
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - ./
      # run unit tests
      - run: npm run ci-test
      - store_test_results:
          path: test-results

  # linting
  lint:
    executor: node-browser
    steps:
      - attach_workspace:
          at: ./
      - run: npm install
      - run: npm run lint

workflows:
  build-test:
    # only run on main and release branches
    when:
      or:
      - equal: [ main, << pipeline.git.branch >> ]
      - matches:
          pattern: "release-*"
          value: << pipeline.git.branch >>

    jobs:
      - test
      - lint:
          requires:
            - test
